doctrine:
    dbal:
        default_connection: bot
        connections:
            bot:
                url: '%env(DATABASE_BOT_URL)%'
            channel:
                url: '%env(DATABASE_CHANNEL_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        default_entity_manager: bot
        auto_generate_proxy_classes: true
        entity_managers:
            bot:
                connection: bot
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Bot:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Bot'
                        prefix: 'App\Entity\Bot'
                        alias: Bot
            channel:
                connection: channel
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Channel:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Channel'
                        prefix: 'App\Entity\Channel'
                        alias: Channel